language: objective-c
osx_image: xcode10.2
xcode_project: $PROJECTNAME.xcodeproj
env:
  global: 
  - PROJECT="$PROJECTNAME.xcodeproj"
  - FRAMEWORK_NAME="$PROJECTNAME.framework"
  - IOS_FRAMEWORK_SCHEME="$PROJECTNAME iOS"
  - MACOS_FRAMEWORK_SCHEME="$PROJECTNAME OSX"
  - TVOS_FRAMEWORK_SCHEME="$PROJECTNAME tvOS"
  - TEST_FRAMEWORK_SCHEME="$PROJECTNAMETests"
  - IOS_SDK=iphonesimulator
  - MACOS_SDK=macosx
  - TVOS_SDK=appletvsimulator
  matrix:
    - DESTINATION="OS=12.2,name=iPad Pro (10.5-inch)"  SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     CARTHAGEDEPLOY="YES"
    - DESTINATION="OS=12.2,name=iPhone 8"              SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     POD="YES"
    - DESTINATION="arch=x86_64"                        SCHEME="$MACOS_FRAMEWORK_SCHEME"   SDK="$MACOS_SDK"
    - DESTINATION="arch=x86_64"                        SCHEME="FilesProviderTests"        SDK="$MACOS_SDK"   RUN_TESTS="YES"
    - DESTINATION="OS=12.2,name=Apple TV 1080p"        SCHEME="$TVOS_FRAMEWORK_SCHEME"    SDK="$TVOS_SDK"
before_install:
  - gem install xcpretty --no-document --quiet
  - gem install cocoapods --no-document --quiet
  # - gem install xcpretty-travis-formatter

script:
  - set -o pipefail
  - xcodebuild -version

  # Build Example in Debug if specified
  - if [ $BUILD_EXAMPLE == "YES" ]; then
      xcodebuild -project "$WORKSPACE" -scheme "$EXAMPLE_SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty;
    fi

  # Build Framework in Debug and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;
    else
      xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty;
    fi

  # Build Framework in Release and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;
    else
      xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty;
    fi

  # Run `pod lib lint` if specified
  - if [ $POD == "YES" ]; then
      pod lib lint --quick;
    fi

after_success:
  # Run `pod trunk push` if specified
  - if [ $POD == "YES" ] && [ -n "$TRAVIS_TAG" ]; then
      pod trunk push --allow-warnings;
    fi

#   - bash <(curl -s https://codecov.io/bash)
before_deploy:
  - if [ $CARTHAGEDEPLOY == "YES" ] && [ -n "$TRAVIS_TAG" ]; then
      brew update;
      brew outdated carthage || brew upgrade carthage;
      carthage version;
      carthage build --no-skip-current --verbose;
      carthage archive $PROJECTNAME;
    fi

deploy:
  provider: releases
  api_key: "$GITHUBTOKEN"
  file: $FRAMEWORK_NAME.zip
  skip_cleanup: true
  on:
    # repo: amosavian/$PROJECTNAME
    repo: amosavian/FileProvider
    tags: true
    condition: "$CARTHAGEDEPLOY = YES"
